##
# Copyright (C) 2022-2023 Hedera Hashgraph, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##

name: "Node: PR Checks"
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

defaults:
  run:
    shell: bash

concurrency:
  group: pr-checks-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Code
    uses: ./.github/workflows/node-zxc-compile-application-code.yaml
    with:
      enable-spotless-check: false
    secrets:
      access-token: ${{ secrets.GITHUB_TOKEN }}
      gradle-cache-username: ${{ secrets.GRADLE_CACHE_USERNAME }}
      gradle-cache-password: ${{ secrets.GRADLE_CACHE_PASSWORD }}

  spotless:
    name: Spotless
    uses: ./.github/workflows/node-zxc-compile-application-code.yaml
    with:
      custom-job-label: "Check"
      enable-unit-tests: false
      enable-e2e-tests: false
      enable-integration-tests: false
      enable-sonar-analysis: false
      enable-spotless-check: true
    secrets:
      access-token: ${{ secrets.GITHUB_TOKEN }}
      gradle-cache-username: ${{ secrets.GRADLE_CACHE_USERNAME }}
      gradle-cache-password: ${{ secrets.GRADLE_CACHE_PASSWORD }}

  unit-tests:
    name: Unit Tests
    uses: ./.github/workflows/node-zxc-compile-application-code.yaml
    with:
      custom-job-label: Standard
      enable-unit-tests: true
      enable-e2e-tests: false
      enable-integration-tests: false
      enable-sonar-analysis: false
    secrets:
      access-token: ${{ secrets.GITHUB_TOKEN }}
      gradle-cache-username: ${{ secrets.GRADLE_CACHE_USERNAME }}
      gradle-cache-password: ${{ secrets.GRADLE_CACHE_PASSWORD }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}

  eet-tests:
    name: E2E Tests
    uses: ./.github/workflows/node-zxc-compile-application-code.yaml
    with:
      custom-job-label: Standard
      enable-unit-tests: false
      enable-e2e-tests: true
      enable-integration-tests: false
      enable-sonar-analysis: false
      enable-network-log-capture: true
    secrets:
      access-token: ${{ secrets.GITHUB_TOKEN }}
      gradle-cache-username: ${{ secrets.GRADLE_CACHE_USERNAME }}
      gradle-cache-password: ${{ secrets.GRADLE_CACHE_PASSWORD }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}

  integration-tests:
    name: Integration Tests
    uses: ./.github/workflows/node-zxc-compile-application-code.yaml
    with:
      custom-job-label: Standard
      enable-unit-tests: false
      enable-e2e-tests: false
      enable-integration-tests: true
      enable-sonar-analysis: false
      enable-network-log-capture: true
    secrets:
      access-token: ${{ secrets.GITHUB_TOKEN }}
      gradle-cache-username: ${{ secrets.GRADLE_CACHE_USERNAME }}
      gradle-cache-password: ${{ secrets.GRADLE_CACHE_PASSWORD }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}

  hapi-tests-misc:
    name: HAPI Tests (Misc)
    uses: ./.github/workflows/node-zxc-compile-application-code.yaml
    with:
      custom-job-label: Standard
      enable-unit-tests: false
      enable-e2e-tests: false
      enable-integration-tests: false
      enable-hapi-tests-misc: true
      enable-sonar-analysis: false
      enable-network-log-capture: true
    secrets:
      access-token: ${{ secrets.GITHUB_TOKEN }}
      gradle-cache-username: ${{ secrets.GRADLE_CACHE_USERNAME }}
      gradle-cache-password: ${{ secrets.GRADLE_CACHE_PASSWORD }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}

  hapi-tests-crypto:
    name: HAPI Tests (Crypto)
    uses: ./.github/workflows/node-zxc-compile-application-code.yaml
    with:
      custom-job-label: Standard
      enable-unit-tests: false
      enable-e2e-tests: false
      enable-integration-tests: false
      enable-hapi-tests-crypto: true
      enable-sonar-analysis: false
      enable-network-log-capture: true
    secrets:
      access-token: ${{ secrets.GITHUB_TOKEN }}
      gradle-cache-username: ${{ secrets.GRADLE_CACHE_USERNAME }}
      gradle-cache-password: ${{ secrets.GRADLE_CACHE_PASSWORD }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}

  hapi-tests-token:
    name: HAPI Tests (Token)
    uses: ./.github/workflows/node-zxc-compile-application-code.yaml
    with:
      custom-job-label: Standard
      enable-unit-tests: false
      enable-e2e-tests: false
      enable-integration-tests: false
      enable-hapi-tests-token: true
      enable-sonar-analysis: false
      enable-network-log-capture: true
    secrets:
      access-token: ${{ secrets.GITHUB_TOKEN }}
      gradle-cache-username: ${{ secrets.GRADLE_CACHE_USERNAME }}
      gradle-cache-password: ${{ secrets.GRADLE_CACHE_PASSWORD }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}

  hapi-tests-smart-contract:
    name: HAPI Tests (Smart Contract)
    uses: ./.github/workflows/node-zxc-compile-application-code.yaml
    with:
      custom-job-label: Standard
      enable-unit-tests: false
      enable-e2e-tests: false
      enable-integration-tests: false
      enable-hapi-tests-smart-contract: true
      enable-sonar-analysis: false
      enable-network-log-capture: true
    secrets:
      access-token: ${{ secrets.GITHUB_TOKEN }}
      gradle-cache-username: ${{ secrets.GRADLE_CACHE_USERNAME }}
      gradle-cache-password: ${{ secrets.GRADLE_CACHE_PASSWORD }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}

  hapi-tests-time-consuming:
    name: HAPI Tests (Time Consuming)
    uses: ./.github/workflows/node-zxc-compile-application-code.yaml
    with:
      custom-job-label: Standard
      enable-unit-tests: false
      enable-e2e-tests: false
      enable-integration-tests: false
      enable-hapi-tests-time-consuming: true
      enable-sonar-analysis: false
      enable-network-log-capture: true
    secrets:
      access-token: ${{ secrets.GITHUB_TOKEN }}
      gradle-cache-username: ${{ secrets.GRADLE_CACHE_USERNAME }}
      gradle-cache-password: ${{ secrets.GRADLE_CACHE_PASSWORD }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}

  abbreviated-panel:
    name: JRS Panel
    uses: ./.github/workflows/zxc-jrs-regression.yaml
    if: ${{ github.actor != 'dependabot[bot]' && github.event.pull_request.head.repo.full_name == github.repository }}
    with:
      custom-job-name: "Platform SDK"
      panel-config: "configs/suites/GCP-PRCheck-Abbrev-4N.json"
      branch-name: ${{ github.head_ref || github.ref_name }}
      base-branch-name: ${{ github.base_ref || '' }}
      slack-results-channel: "regression-test"
      slack-summary-channel: "regression-test"
      use-branch-for-slack-channel: false
    secrets:
      access-token: ${{ secrets.PLATFORM_GH_ACCESS_TOKEN }}
      gradle-cache-username: ${{ secrets.GRADLE_CACHE_USERNAME }}
      gradle-cache-password: ${{ secrets.GRADLE_CACHE_PASSWORD }}
      jrs-ssh-user-name: ${{ secrets.PLATFORM_JRS_SSH_USER_NAME }}
      jrs-ssh-key-file: ${{ secrets.PLATFORM_JRS_SSH_KEY_FILE }}
      gcp-project-number: ${{ secrets.PLATFORM_GCP_PROJECT_NUMBER }}
      gcp-sa-key-contents: ${{ secrets.PLATFORM_GCP_KEY_FILE }}
      slack-api-token: ${{ secrets.PLATFORM_SLACK_API_TOKEN }}

  snyk-scan:
    name: Snyk Scan
    uses: ./.github/workflows/node-zxc-compile-application-code.yaml
    with:
      custom-job-label: Standard
      enable-unit-tests: false
      enable-e2e-tests: false
      enable-integration-tests: false
      enable-sonar-analysis: false
      enable-snyk-scan: true
    secrets:
      access-token: ${{ secrets.GITHUB_TOKEN }}
      gradle-cache-username: ${{ secrets.GRADLE_CACHE_USERNAME }}
      gradle-cache-password: ${{ secrets.GRADLE_CACHE_PASSWORD }}
      snyk-token: ${{ secrets.SNYK_TOKEN }}
